[package]
name = "asaborake-ts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "MPEG-2 TS demultiplexing and inventory for Asaborake"

[lints]
workspace = true

[dependencies]
encoding_rs = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
